import GlassPane from '@/components/GlassPane';
import '@/styles/globals.css';
import clsx from 'clsx';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang='en'
      className={clsx(inter.className, 'dark')}
    >
      <body className='h-screen w-screen candy-mesh p-6'>
        <GlassPane className='w-full h-full p-6 flex align-center container mx-auto'>
          <main className='w-full pl-6 h-full'>{children}</main>
        </GlassPane>
      </body>
    </html>
  );
}
